image: python:3.9-slim

before_script:
  - apt-get update && apt-get install -y git
  - pip install -r requirements.txt

pages:
  script:
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  only:
    - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH